**Text Preprocessing Techniques**
* LowerCase
* Tokenization
* Spelling Correction
* Emoji Prediction
* URLs/html tags removal
* Punctuation marke removal
* Numbers removal
* StopWords removal
* Stemming and Lemmatization

In [25]:
import pandas as pd
from nltk.tokenize import word_tokenize , sent_tokenize

In [13]:
df = pd.read_csv(r"C:\Users\User\Downloads\Telegram Desktop\Emotions .csv")
df

        Unnamed: 0                                               text  label
0                0      i just feel really helpless and heavy hearted      4
1                1  ive enjoyed being able to slouch about relax a...      0
2                2  i gave up my internship with the dmrg and am f...      4
3                3                         i dont know i feel so lost      0
4                4  i am a kindergarten teacher and i am thoroughl...      4
...            ...                                                ...    ...
416804      416804  i feel like telling these horny devils to find...      2
416805      416805  i began to realize that when i was feeling agi...      3
416806      416806  i feel very curious be why previous early dawn...      5
416807      416807  i feel that becuase of the tyranical nature of...      3
416808      416808  i think that after i had spent some time inves...      5

[416809 rows x 3 columns]

In [15]:
df.drop("Unnamed: 0" , axis = 1 , inplace = True)

In [16]:
df.rename(columns={'text' : "Text"} , inplace=True)
df.rename(columns={'label' : "Label"} , inplace=True)

In [17]:
df

                                                     Text  Label
0           i just feel really helpless and heavy hearted      4
1       ive enjoyed being able to slouch about relax a...      0
2       i gave up my internship with the dmrg and am f...      4
3                              i dont know i feel so lost      0
4       i am a kindergarten teacher and i am thoroughl...      4
...                                                   ...    ...
416804  i feel like telling these horny devils to find...      2
416805  i began to realize that when i was feeling agi...      3
416806  i feel very curious be why previous early dawn...      5
416807  i feel that becuase of the tyranical nature of...      3
416808  i think that after i had spent some time inves...      5

[416809 rows x 2 columns]

**LowerCase**

In [23]:
df['Text'] = df['Text'].str.lower()

In [24]:
df

                                                     Text  Label
0           i just feel really helpless and heavy hearted      4
1       ive enjoyed being able to slouch about relax a...      0
2       i gave up my internship with the dmrg and am f...      4
3                              i dont know i feel so lost      0
4       i am a kindergarten teacher and i am thoroughl...      4
...                                                   ...    ...
416804  i feel like telling these horny devils to find...      2
416805  i began to realize that when i was feeling agi...      3
416806  i feel very curious be why previous early dawn...      5
416807  i feel that becuase of the tyranical nature of...      3
416808  i think that after i had spent some time inves...      5

[416809 rows x 2 columns]

In [33]:
for i in df['Text']:
    print(word_tokenize(i))

KeyboardInterrupt:

In [34]:
df[0:50000:1]

                                                    Text  Label
0          i just feel really helpless and heavy hearted      4
1      ive enjoyed being able to slouch about relax a...      0
2      i gave up my internship with the dmrg and am f...      4
3                             i dont know i feel so lost      0
4      i am a kindergarten teacher and i am thoroughl...      4
...                                                  ...    ...
49995  i will flush all the crap and the fat out so i...      1
49996  i can think of a few things that i feel like w...      1
49997  i would recommend it to anyone who feels dissa...      3
49998  i think that what i m feeling here goes a lot ...      1
49999  i feel homesick when i have the barcelona team...      0

[50000 rows x 2 columns]